(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=this||self;function f(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};/*
 Copyright 2022 Glance Networks, Inc.
*/
var l=["6","2","0","37"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var n=navigator.userAgent.toLowerCase(),ba=n.match(/(edge)[\s\/:]([\w\d\.]+)?/)||n.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||n.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===ba[1]&&(ba[1]="ie");function ca(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function p(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(ca(arguments))}function da(a){window.console&&window.console.error&&window.console.error(ca(arguments))};function q(){this.a={}}q.prototype.add=function(a,b){this.a[a]=this.a[a]||[];this.a[a].push(b)};q.prototype.h=function(a,b){b&&JSON.stringify(b);var c=this.a[a],d=!0;if(void 0===c)return!0;for(a=0;a<c.length;a++)c[a](b)||(d=!1);return d};/*
 Copyright (c) 2022 Glance Networks, Inc.
 Copyright 2022 Glance Networks, Inc.
*/
var ea=ea||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.2.0.26";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var u=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==c[1]&&c[4]?c[4]:c[2]),o:{name:a.match(/ip(?:ad|od|hone)/)||
b.match(/mac/)&&"undefined"!==typeof navigator.a?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},ia:{qa:!!document.evaluate,ka:!!window.na,query:!!document.querySelector,json:!!window.JSON},ja:{},la:function(){return"ios"==this.o.name||"android"==this.o.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&(a.name="ie",a.version="7");a[a.name]=
!0;a[a.name+parseInt(a.version,10)]=!0;a.o[a.o.name]=!0;return a}();if(void 0===v)var v=function(a){return JSON.stringify(a)};function fa(a){a.onmessage=function(b){b=JSON.parse(b.data);a.O&&a.O(b)};a.v=function(b){b=v(b);a.send(b)};a.W=function(b){return b&&b.code||0};a.X=function(b){return b&&b.reason||""}}function ha(a){a=new WebSocket(a);fa(a);return a}function ia(a,b){w(window,"setTimeout",function(){ia(a,b)},100)}
function x(a,b,c){void 0!==a&&(c=c||Object.keys(a),c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])}))}function ja(a){var b=a.func.split(".");if(2>b.length)y("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){y("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else y("ERR_BADINVOKE:"+b[0])}
async function ka(a,b){return new Promise(async(c,d)=>{b.headers={"Content-Type":"application/json"};"object"===typeof b.body&&(b.body=JSON.stringify(b.body));let e;try{e=await fetch(a,b)}catch(k){y(`JSON request to ${a} failed: ${k.message}`);d("connection");return}if(e.ok){try{var h=await e.json()}catch(k){y(`JSON request to ${a} reponse parse failed`),d("error")}c(h)}else y(`JSON request to ${a} failed status: ${e.status}`),c=await e.text(),y(c),d(401===e.status||403===e.status?"authorization":
"error")})}function z(){ea.pa?this.f=new A("JSON"):this.a=new window.XMLHttpRequest;this.response=null;this.type="JSON"}z.prototype.abort=function(){this.f?this.f.abort():this.a.abort()};
z.prototype.onreadystatechange=function(){if(4==this.a.readyState){w(window,"clearTimeout",this.i);delete this.i;var a="error";if(0==this.a.status)B(this.method+" to "+this.url+" failed: network"),this.b(!0,"connection",this.a.status);else if(200!==this.a.status){y(this.method+" to "+this.url+" failed with status: "+this.a.status);"text"===this.a.responseType&&null!==this.a.responseText&&B(this.a.responseText);if(401===this.a.status||403===this.a.status)a="authorization",this.c&&this.c.I();this.b(!1,
a,this.a.status)}else{if(""!==this.a.response){if("XML"===this.accept)this.response=this.a.responseXML&&this.a.responseXML.documentElement,null===this.response&&y("Invalid XML response: "+this.a.responseText);else if(this.u){for(var b=new Uint8Array(this.a.responseText.length),c=0;c<this.a.responseText.length;c++)b[c]=this.a.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.a.getResponseHeader("Content-Type")})}else if("blob"===this.a.responseType)this.response=this.a.response;
else if(this.a.responseXML)this.response=la(this.a.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.a.responseText;else if(this.response=la(this.a.responseText),null===this.response){B(this.method+" to "+this.url+" failed - can't parse response "+this.a.responseText);this.b(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){B(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.b(!1,a);return}}this.onsuccess(this.response)}}};function la(a){var b=null;try{b=JSON.parse(a)}catch(c){return B("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}z.prototype.getResponseHeader=function(a){return this.a.getResponseHeader(a)};z.prototype.get=function(a,b,c,d,e){this.method="GET";D(this,a,null,b,c,d,e)};
function D(a,b,c,d,e,h,k){a.url=b;a.onsuccess=void 0!==h?h:function(){};a.b=void 0!==k?k:function(){};a.method=a.method||"POST";if(a.f)ma(a.f,b,c,d,e,h,k);else{h=a.B||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var g=c;else c instanceof Blob?(h=c.type,g=c):c&&(g="JSON"===a.type?v(c):"data="+v(c));u.safari&&a.m&&(a.i=w(window,"setTimeout",function(){B(this.method+" to "+this.url+" failed - timedout (Safari)");this.b(!1,
"timedout")}.bind(a),a.m));a.a.onreadystatechange=function(){a.onreadystatechange()};try{a.a.open(a.method,b,d),void 0!==a.j&&a.a.setRequestHeader("Accept",a.j),void 0!==a.a.setRequestHeader&&"GET"!==a.method&&a.a.setRequestHeader("Content-type",h),a.c&&a.c.s()?a.a.setRequestHeader("Authorization","Bearer "+a.c.s()):a.l&&a.a.setRequestHeader("Authorization","Bearer "+a.l),a.a.withCredentials=e,a.a.send(g)}catch(r){B(a.method+" to "+b+" failed with: "+r.toString()),a.b(!1,r.toString())}}}
function A(a){this.type=a}function ma(a,b,c,d,e,h,k){a.onsuccess=h;a.b=k;ia({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:e})}A.prototype.abort=function(){A.postMessage({from:"IFrameProxyRequest",abort:!0})};function E(a){this.name=a}function oa(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);localStorage.setItem(a.name,v(b));localStorage.setItem(a.name+"_exp",c.toGMTString())}function F(a){if(!pa(a))return null;a=localStorage.getItem(a.name);return JSON.parse(a)}
function qa(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);localStorage.setItem(a.name+"_exp",c.toGMTString())}E.prototype.get=function(){return pa(this)?localStorage.getItem(this.name):null};function G(a){localStorage.removeItem(a.name);localStorage.removeItem(a.name+"_exp")}function pa(a){var b=localStorage.getItem(a.name+"_exp");if(!b)return!1;b=new Date(b);return b<new Date?(G(a),!1):!0}
function H(){var a=window;this.a=a.document;this.b=a;var b=[["hidden","visibilitychange"],["mozHidden","mozvisibilitychange"],["webkitHidden","webkitvisibilitychange"],["msHidden","msvisibilitychange"],["oHidden","ovisibilitychange"]];for(a=0;a<b.length&&!(b[a][0]in document);a++);}H.prototype.getElementsByTagName=function(a){return w(this.a,"getElementsByTagName",a)};
function ra(a,b){var c=[["src","//www.glancecdn.net/cobrowse/js/sockjs1.0.2.min.js"]],d=a.a.createElement("script");b&&d.addEventListener("load",b);d.setAttribute("type","text/javascript");d.setAttribute("charset","UTF-8");for(b=0;b<c.length;b++)d.setAttribute(c[b][0],c[b][1]);a.a.head.appendChild(d)}H.prototype.head=function(){return void 0!==this.a.head?this.a.head:this.getElementsByTagName("head")[0]};
function sa(a){if(void 0!==window.pageXOffset)return{x:Math.round(a.b.pageXOffset),y:Math.round(a.b.pageYOffset)};if(void 0!==document.documentElement.scrollTop)return{x:a.a.documentElement.scrollLeft,y:a.a.documentElement.scrollTop};if(void 0!==document.body.scrollLeft)return{x:a.a.body.scrollLeft,y:a.a.body.scrollTop};throw Error("Can't get page scroll");}
H.prototype.scrollTo=function(a,b,c){var d=sa(this);d[a]=b;a={left:d.x,top:d.y,behavior:c?"smooth":"auto"};u.ie11||u.edge?window.scrollTo(d.x,d.y):window.scrollTo(a);sa(this)};H.prototype.addEventListener=function(a,b,c){w(this.a,"addEventListener",a,b,c)};H.prototype.removeEventListener=function(a,b,c){w(this.a,"removeEventListener",a,b,c)};function I(a){this.a=a}I.prototype.addEventListener=function(a,b,c){w(this.a,"addEventListener",b,c)};
I.prototype.removeEventListener=function(a,b,c){w(this.a,"removeEventListener",b,c)};function w(a,b,...c){return I.b&&I.a&&a.nodeType?"#document"===a.nodeName?I.a.document[b].apply(a,c):"#document-fragment"===a.nodeName?I.a.DocumentFragment.prototype[b].apply(a,c):I.a.document.body[b].apply(a,c):I.b&&I.a&&"[object Window]"===a.toString()?I.a.window[b].apply(a,c):a[b].apply(a,c)}function ta(a,b,c){a.a.style.left=b+"px";a.a.style.top=c+"px"}
I.prototype.moveTo=function(a,b){function c(){10>k++?(e+=g,h+=r,ta(d,Math.floor(e),Math.floor(h)),d.b=w(window,"setTimeout",c,20)):ta(d,a,b)}void 0!==this.b&&w(window,"clearTimeout",this.b);var d=this,e=parseInt(this.a.style.left),h=parseInt(this.a.style.top);isNaN(e)&&(e=-999);isNaN(h)&&(h=-999);var k=0,g=(a-e)/10,r=(b-h)/10;0===g&&0===r||c()};
function ua(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function B(...a){ua("log",...a)}function y(...a){ua("error",...a)}function K(...a){B("PRES:",...a)};function va(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function wa(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function xa(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("glance-cobrowse"),c=wa(document.getElementById("cobrowsescript"));b=wa(b);va(c,a);va(b,a);return a};var L={};f("GLANCE.Authorization",L);L.da=function(a){L.F=a};L.setToken=L.da;L.s=function(){var a=xa();return a.authtoken?a.authtoken:L.F||L.g&&F(L.g)};L.I=function(){delete L.F;L.g&&(G(L.g),delete L.g)};L.clearToken=L.I;L.H=function(){return L.s()?!0:!1};L.authorized=L.H;
L.G=async function(a){L.g=L.g||new E("glanceauth");if(!L.H()){var b=`https://${a.ws||"www.glance.net"}/services/AuthorizationService.svc/rest/${a.credentials?"Authorize":"AuthorizeFromWebSession"}?groupid=${a.groupid}&service=${a.service}&duration=${a.duration}&site=${a.site||"production"}`,c;a.credentials?c={method:"post",mode:"cors",body:a.credentials}:c={method:"post",mode:"same-origin",credentials:"include"};try{var d=await ka(b,c)}catch(e){a.onfail(e);return}oa(L.g,d);qa(L.g,a.duration)}if(a.onsuccess)a.onsuccess()};
L.authorize=L.G;function M(){}function ya(a,b){a.P="undefined"===typeof WebSocket;a.a={};a.a.ws="www.glance.net";a.a.site="production";a.ha=new H;x(xa(),a.a);x(b,a.a);delete a.a.presenceserver;a.u=[];a.f=N;a.m=new E("glance_presence");var c=F(a.m);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.a[d]).length?a.c=c.directserver:K("Ignoring glance_presence entry for different visitor",c.groupid,c.visitorid));K("direct server from local storage:",a.c)}var N=1;
function za(a,b,c,d,e){if(b&&!a.c)p("ERR_NODIRECTSERVER");else{var h=(e||"https")+"://"+(b?a.c:a.a.presenceserver)+"/"+c;d&&(h+="?",["groupid","visitorid"].forEach(function(k){h+=k+"="+a.a[k]+"&"}),h+=`&ver=${l}`);return h}}function Aa(a,b){O(a,!1,"findvisitor","GET",b)}
function P(a){p("connecting to "+a.c);var b=!1;a.P&&!window.SockJS?ra(a.ha,function(){b||(K("sockjs script added"),b=!0,window.SockJS?P(a):p("ERR_NOSOCKJS"))}):(a.b&&a.b.close(),a.b=ha(za(a,!0,"agent",!1,"wss")),a.b.R=a.c,a.b.onopen=function(){K("sock onopen, sending connect");a.b.v({type:"connect",authorization:a.i&&a.i.s(),groupid:a.a.groupid,visitorid:a.a.visitorid,guesttoken:a.a.guesttoken,version:l});K("sending message queue");a.u.forEach(function(c){a.b.v(c)});a.u=[];a.f=3},a.b.O=function(c){p("received:"+
v(c));if(a.b){var d=c.mtype||c.type,e=c.data;switch(d){case "connected":if(a.a.nokeepalive)break;K("Keepalive interval: "+c.keepalive);a.j||(a.j=window.setInterval(function(){a.b.v({type:"k"})},1E3*c.keepalive));break;case "invoke":"visitor"===a.S&&ja(e);break;case "redirect":case "serverclose":e||(e=c);default:if(a["on"+d])a["on"+d](e)}}else K("Ignoring message received after socket close")},a.b.onclose=function(c){a.b===this&&(p(`presence connection closed ${this.W(c)} ${this.X(c)}`),Ba(a),Ca(a))},
a.b.onerror=function(c){a.b===this&&(K("socket error"),a.P=!0,a.b.onclose(c))})}M.prototype.i=void 0;
function O(a,b,c,d,e){function h(t){var m=t&&(t.directserver||t.direct);!b&&m&&(g.c=m,t.httpsport&&(g.c+=":"+t.httpsport));g.b&&g.c!=g.b.R&&(K("switching connection from "+g.b.R+" to "+g.c),P(g));if(e&&e.onsuccess)e.onsuccess(t)}function k(t,m,C){p(`Presence request: ${c} failed reason: ${m} http status: ${C||0}`);503===C&&(da("Presence service unavailable"),g.N=!0,m="serviceunavailable");if(e.onfail)e.onfail(m);else Da(g,{error:"connfail",detail:m})}if(!a.N){var g=a,r=new z;r.c=a.i;r.method=d;p(c,
JSON.stringify(e));(function(t){if(g.a.presenceserver)return t();var m=new E("glance_visitor_settings_"+g.a.groupid+"_"+g.a.site),C=F(m);if(C)return g.a.presenceserver=C.presenceserver,g.a.presenceserver||p("PRES_DISABLED (from cache)"),t();C=new z;var Ia="https://"+g.a.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+g.a.groupid+"&site="+g.a.site+"&service=presence";C.method="GET";D(C,Ia,null,!0,!1,function(Y){g.a.presenceserver=Y.presenceUrl;K("presence service: "+g.a.presenceserver);
g.a.presenceserver||p("PRES_DISABLED");var J={};J.presenceserver=g.a.presenceserver;J.presencesettings=Y;oa(m,J);qa(m,1440);return t()},function(Y,J){p("PRES_UNAVAILABLE "+J);t()})})(function(){g.a.presenceserver&&D(r,za(g,b,c,!0),e.data?e.data:{},!0,!1,h,k)})}}function Ba(a){a.j&&(window.clearInterval(a.j),delete a.j);a.f=N;delete a.b;delete a.c}M.prototype.ea=function(a){let b=3===this.f;b&&this.disconnect();this.a.visitorid=a;(b||"api"!==this.a.presence)&&this.connect()};
M.prototype.setVisitorId=M.prototype.ea;
M.prototype.connect=function(){if(!this.N)if(this.a.visitorid)if(this.f!==N)K("connect() called when already connecting or connected");else{this.f=2;K("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){K("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.c);this.m&&b.direct!==this.c&&(G(this.m),this.m=new E("glance_presence"),this.disconnect(),Ca(this))};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
this.c?P(this):Aa(this,{onsuccess:function(){p("found visitor, connect");P(a)},onfail:function(b){a.f=N;Da(a,{error:"connfail",detail:b})}})}else p("CONN_NOVISITORID")};M.prototype.connect=M.prototype.connect;M.prototype.disconnect=function(){K("closewebsocket");this.b&&this.b.close();Ba(this)};M.prototype.disconnect=M.prototype.disconnect;
function Ca(a){K(`delayed reconnect.  count: ${a.l||0} connstate: ${a.f}`);a.B||(a.l=a.l||0,a.l++,a.B=window.setTimeout(()=>{delete a.B;a.connect()},3>=a.l?5E3:6E4))}function Da(a,b){p("Error: ",JSON.stringify(b));a.ga&&a.ga(b);if(a.onerror)a.onerror(b)}M.prototype.h=function(a,b){a={type:a,data:b};p("sending",a.type,this.f);3===this.f?(K("sending message: "+JSON.stringify(a)),this.b.v(a)):(K("queuing message: "+JSON.stringify(a)),this.u.push(a),this.connect())};M.prototype.fire=M.prototype.h;function Q(a){a.uniqueid&&(a.visitorid="UNQ-"+a.uniqueid);ya(this,a);this.S="agent"}f("GLANCE.Presence.Agent",Q);Q.prototype=new M;Q.prototype.i=L;function Ea(a,b,c,d,e){e=e||function(h){B("Unhandled error:"+JSON.stringify(h))};Aa(a,{onsuccess:function(h){h.visitorfound?O(a,!0,"signalvisitor","POST",{data:{mtype:b,data:c},onsuccess:d,onfail:e}):(B("ERR_VISITORNOTPRESENT"),e("visitornotpresent"))},onfail:e})}Q.prototype.fa=function(a){Ea(this,"signal",a.data,a.onsuccess,a.onfail)};
Q.prototype.signalVisitor=Q.prototype.fa;Q.prototype.J=function(a){var b={};x(a,b,["func","args"]);Ea(this,"invoke",b,a.onsuccess,a.onfail)};Q.prototype.invokeVisitor=Q.prototype.J;
Q.prototype.M=function(a){const b=a.onsuccess;a.onsuccess=function(c){Object.keys(c).forEach(function(d){if("string"===typeof c[d]&&0===c[d].indexOf("{'"))try{K("Converting python object to json:",c[d]),c[d]=JSON.parse(c[d].replace(/'/g,'"'))}catch(e){B("Could not convert "+c[d]+" to json")}});b(c)};O(this,!1,"lookupvisitor","GET",a)};Q.prototype.lookupVisitor=Q.prototype.M;Q.prototype.query=function(a){O(this,!1,"query","GET",a)};Q.prototype.query=Q.prototype.query;/*
 Copyright (c) 2020-2021 Glance Networks, Inc.
 The GlanceAgent JavaScript can be included in a customer or partner page to join and control
 sessions as an agent, by opening and communicating with /agentjoin/AgentView.aspx
*/
var R=R||{};f("GLANCE.Agent",R);R.webserver="https://www.glance.net";R.postParametersToViewer=!0;var S={},T={},U=new q,V,W=!1;window.addEventListener("message",function(a){const b=a.data.glanceEvent;b&&(a.origin!==R.webserver?p("Glance Agent not handling message from "+a.origin+" not matching "+R.webserver):(U.h(b,a.data.data),U.h("*",a.data)))});function X(a,b){U.h(a,b);U.h("*",{glanceEvent:a,data:b})}
R.aa=function(a,b={}){p("GLANCE.Agent.openViewer");var c="";S&&S.partnerid&&S.partneruserid&&S.loginkey&&(c="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey);return R.C(R.webserver+"/agentjoin/AgentView.aspx?SessionKey="+a+"&"+c,b)};R.openViewer=R.aa;
R.C=function(a,b={}){p("GLANCE.Agent.openAgentJoinURL");if(b&&b.iframe){var c="string"===typeof b.iframe?document.getElementById(b.iframe):b.iframe,d,e,h=new Promise((k,g)=>{d=k;e=g});c.onload=function(){let k=c.contentWindow;k?d(k):(X("iframeblocked",{service:"agent"}),e())};R.postParametersToViewer?Fa(c.contentWindow,a,b):c.src=a;return h}{let k;R.postParametersToViewer?(k=window.open("",b.windowName||"_blank",b.windowFeatures||"referrerpolicy==no-referrer,location=no,menubar=0,titlebar=0,status=0,toolbar=0,height=800,width=800,top=10,left=10,scrollbars=1,resizable=1"),
Fa(k,a,b)):k=window.open(a,b.windowName||"_blank",b.windowFeatures||"referrerpolicy==no-referrer,location=no,menubar=0,titlebar=0,status=0,toolbar=0,height=800,width=800,top=10,left=10,scrollbars=1,resizable=1");k?X("viewerOpened",{service:"agent",close:()=>R.close(k)}):X("popupblocked",{service:"agent"});return new Promise((g,r)=>{k?g(k):r()})}};R.openAgentJoinURL=R.C;
function Fa(a,b,c={}){("undefined"==typeof b||0>b.toLowerCase().indexOf("sessionkey="))&&p("No session key");var d=document.createElement("form");d.method="POST";d.action=R.webserver+"/agentjoin/AgentView.aspx";var e=Z("wait","1");"false"===c.wait&&(e=Z("wait","0"));d.appendChild(e);null!=c.agentVideo&&(e=Z("agentVideo","true"===c.agentVideo?"1":"0"),d.appendChild(e));if(S&&S.partnerid&&S.partneruserid&&S.loginkey){e=Z("loginkey",S.loginkey);var h=Z("partnerid",S.partnerid),k=Z("partneruserid",S.partneruserid);
d.appendChild(e);d.appendChild(h);d.appendChild(k)}e=document.createElement("script");e.innerText="document.forms[0].submit()";d.appendChild(e);e={};if(b){b=b.split("?")[1].split("&");for(g in b){let [t,m]=b[g].split("=");e[t]=m}var g=e}else g={};for(var r in g){b=!1;for(e=0;e<d.elements.length;e++)b=b||d.elements[e].name.toUpperCase()===r.toUpperCase();b?d[r.toUpperCase()].value=g[r]:d.appendChild(Z(r,g[r]))}for(let t in c){r=!1;for(g=0;g<d.elements.length;g++)r=r||d.elements[g].name.toUpperCase()===
t.toUpperCase();r||d.appendChild(Z(t,c[t]))}a.document.body.appendChild(d)}function Z(a,b){var c=document.createElement("input");c.type="hidden";c.name=a.toUpperCase();c.value="undefined"==typeof b?"":b;return c}R.end=function(){p("GLANCE.Agent.end not implemented")};R.end=R.end;R.addEventListener=function(a,b){U.add(a,b)};R.addEventListener=R.addEventListener;R.T=function(a){U.add("*",function(b){a(b.glanceEvent,b.data)})};R.addEventListenerAll=R.T;
R.removeEventListener=function(a,b){a=U.a[a];void 0!==a&&(b=a.indexOf(b),0<=b&&a.splice(b,1))};R.removeEventListener=R.removeEventListener;R.U=function(a){p("GLANCE.Agent.authenticate");S=a;for(var b of["idpid","idpname","idptoken","idpusername"])if("undefined"!=typeof S[b]){Ga(b,S[b]);break}};R.authenticate=R.U;
function Ga(a,b){Ha(R.webserver+"/account/getloginkey.aspx?sso=1&mode=embedded&fmt=html&"+(a+"="+b));var c=0;W=!0;var d=setInterval(function(){W?3<c?(W=!1,U.h("authenticateFailed",{}),clearInterval(d)):(c++,p("SAML authentication pending attmept: "+c)):clearInterval(d)},3E3);R.removeEventListener("authenticateSucceeded",Ja);R.addEventListener("authenticateSucceeded",Ja);R.removeEventListener("authenticateFailed",Ka);R.addEventListener("authenticateFailed",Ka)}
function Ha(a){var b=document.createElement("iframe");b.src=a;b.style.display="none";b.style.height="0";b.style.width="0";b.id="glanceSsoIframe";document.body.appendChild(b)}
function Ja(a){W=!1;a=a.loginKey;"undefined"!=typeof a&&0<a.indexOf("~")?(a=a.split("~"),S.loginkey=a[1],0<a[0].indexOf("&")?(a=a[0].split("&"),0==a[0].indexOf("partnerid")?(S.partnerid=a[0].split("=")[1],S.partneruserid=a[1].split("=")[1]):0==a[0].indexOf("partneruserid")?(S.partnerid=a[1].split("=")[1],S.partneruserid=a[0].split("=")[1]):p("Wrong Login Key format")):p("Wrong Login Key format")):p("Wrong Login Key format");null!=document.getElementById("glanceSsoIframe")&&document.getElementById("glanceSsoIframe").remove();
p("SAML authentication succeed")}function Ka(){W=!1;null!=document.getElementById("glanceSsoIframe")&&document.getElementById("glanceSsoIframe").remove();p("SAML authentication failed")}R.$=function(){p("GLANCE.Agent.logout");S={}};R.logout=R.$;
R.L=function(a,b=!0){p("GLANCE.Agent.lookupSession");if(0===Object.keys(S||{}).length)return new Promise((k,g)=>g());var c={index:0,A:!1};let d=()=>{V=null;c.index=0;c.A=!0};V=c;const e=R.webserver+"/services/SessionService.asmx/LookupPartnerSession2";let h="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey+"&ssnkey="+a;return new Promise((k,g)=>{function r(){if(c.A)X("lookupCanceled",{service:"agent",ssnkey:a}),g();else if(12<=c.index)X("lookupFailed",{service:"agent",
ssnkey:a,reason:"timedout"}),g();else{X("lookupWaiting",{service:"agent",ssnkey:a,cancel:d});var t="";fetch(e,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:h}).then(m=>m.text()).then(m=>{t=m;return(new window.DOMParser).parseFromString(m,"text/xml")}).then(m=>{m.getElementsByTagName("agentjoinurl")[0]?(m={service:"agent",id:m.getElementsByTagName("id")[0].textContent,ssnid:m.getElementsByTagName("ssnid")[0].textContent,serverip:m.getElementsByTagName("serverip")[0].textContent,
servername:m.getElementsByTagName("servername")[0].textContent,personid:m.getElementsByTagName("personid")[0].textContent,grpupid:m.getElementsByTagName("groupid")[0].textContent,passcode:m.getElementsByTagName("passcode")[0].textContent,agentjoinurl:m.getElementsByTagName("agentjoinurl")[0].textContent,clientjoinurl:m.getElementsByTagName("clientjoinurl")[0].textContent,visitorversion:m.getElementsByTagName("visitorversion")[0].textContent},X("lookupFound",m),k(m)):"0"===m.getElementsByTagName("id")[0].textContent?
b?setTimeout(r,1E3*(6>=++c.index?3:5)):(X("lookupFailed",{service:"agent",reason:"not found"}),g()):(X("lookupFailed",{service:"agent",reason:t}),g())}).catch(m=>{X("lookupFailed",{service:"agent",reason:t||m.toString()});g()})}}r()})};R.lookupSession=R.L;R.Y=function(a){p("GLANCE.Agent.inSession");return 0===Object.keys(S||{}).length?new Promise((b,c)=>c()):new Promise(b=>{(function(){X("inSession",{service:"agent",ssnkey:a});R.D(a).then(c=>{a?b(c.inSession):b(c.sessionsList)})})()})};
R.inSession=R.Y;R.K=function(a,b={}){p("GLANCE.Agent.joinSession");return new Promise((c,d)=>{let e;R.L(a,null!=(e=b.wait)?e:!0).then(h=>{R.C(h.agentjoinurl,b).then(k=>{c(k)})},d)})};R.joinSession=R.K;
R.D=function(a){if(0===Object.keys(S||{}).length)return new Promise((d,e)=>e());const b=R.webserver+"/services/SessionService.asmx/AgentInSession";let c="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey+"&ssnkey="+(a||"");return new Promise((d,e)=>{(function(){X("inSessionLookup",{service:"agent"});fetch(b,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:c}).then(h=>h.text()).then(h=>(new window.DOMParser).parseFromString(h,"text/xml")).then(h=>
{h=h.getElementsByTagName("session2");let k=[];for(let g=0;g<h.length;g++)k.push({id:h[g].getElementsByTagName("id")[0].textContent,ssnkey:h[g].getElementsByTagName("passcode")[0].textContent,num:h[g].getElementsByTagName("num")[0].textContent,disambiguateId:h[g].getElementsByTagName("disambiguateId")[0].textContent,servername:h[g].getElementsByTagName("servername")[0].textContent});d({inSession:0!=h.length,sessionsList:k})}).catch(h=>e(h))})()})};
R.Z=function(a){return 0===Object.keys(S||{}).length?new Promise((b,c)=>c()):new Promise((b,c)=>R.D("").then(d=>{d=d.sessionsList.filter(e=>e.ssnkey==a)[0];void 0===d&&c(`No Session with sessionkey ${a}`);return fetch("https://"+d.servername+"/agent/message",{method:"POST",mode:"cors",cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json"},redirect:"error",referrerPolicy:"no-referrer",body:"{"+`"ssnid": "${S.partnerid}.${d.ssnkey}.${d.disambiguateId}",`+`"num": ${d.num},`+
'"mtype": "EjectAgent","data": {"reason":"leave"}}'}).then(e=>b(e.ok))}))};R.leaveSession=R.Z;R.V=function(){V&&(p("GLANCE.Agent.cancelLookup"),V.A=!0)};R.cancelLookup=R.V;R.close=function(a){p("GLANCE.Agent.close");a&&a.close();X("viewerClosed",{service:"agent"})};R.close=R.close;
R.ba=function(a){p("GLANCE.Agent.presenceConnect");return new Promise((b,c)=>{Q||c("Glance Presence Agent undefined");if(0===Object.keys(S||{}).length){let d={oa:"presence",reason:"no credentials"};X("presenceFailed",d);c(d)}try{console.log(S),L.G({ws:(new URL(R.webserver)).host,service:"presence",credentials:{partneruserid:S.partneruserid,loginkey:S.loginkey,partnerid:S.partnerid},groupid:S.partnerid,duration:120,onsuccess:d=>{X("presenceAuthorized",{service:"presence",data:d});T=new Q({ws:(new URL(R.webserver)).host,
groupid:S.partnerid,visitorid:a});T.onvisitorconn=e=>{console.log("onvisitorconn","Agent.js");X("visitorConnected",e);T.M({onsuccess:h=>{X("visitorData",h);b(h)},onfail:h=>{X("lookupFailed",h);c(h)}})};T.onpresence=e=>{X("presence",e)};T.onterms=e=>{X("presenceOnTerms",e)};T.onvisitorsessionend=e=>{X("presenceSessionEnd",e)};T.onerror=e=>{X("presenceError",e)};T.onvisibility=e=>{X("presenceVisibility",e)};T.connect()},onfail:d=>{X("presenceFailed",{service:"presence",reason:d});c(d)}})}catch(d){X("presenceFailed",
{service:"presence",reason:d}),c(d)}})};R.presenceConnect=R.ba;
R.ca=function(a,b,c){p("GLANCE.Agent.presenceStartSession");let d=b||{};d.func=d.func||"GLANCE.Cobrowse.VisitorUI.showTerms";d.args=d.args||{};let e=a||d.args.sessionKey||Math.floor(1E4*Math.random());return new Promise(function(h,k){Q||k("Glance Presence Agent undefined");d.args.sessionKey=e;d.onfail=function(g){X("presenceInvokeFailed",{service:"presence",reason:g});k(g)};T.onvisitorsessionstart=()=>{X("presenceSessionStart",{});h(R.K(e,c))};T.J(d)})};R.presenceStartSession=R.ca;
R.ma=function(){p("GLANCE.Agent.presenceDisconnect");T.disconnect()};window.addEventListener("beforeunload",function(){console.log("unload")});}).call(window);
