(function() {/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self;function f(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};/*
 Copyright 2022 Glance Networks, Inc.
*/
var l=["6","19","0","1197459447"].slice(0,3).join(".");Uint8Array.prototype.slice||(Uint8Array.prototype.slice=function(a,b){return new Uint8Array(this.subarray(a,b))});
ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var c=new ArrayBuffer(b-a),d=new Uint8Array(c);a=new Uint8Array(this,a,b-a);d.set(a);return c});
var m=navigator.userAgent.toLowerCase(),p=m.match(/(edge)[\s\/:]([\w\d\.]+)?/)||m.match(/(opera|ie|firefox|chrome|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||m.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"rv"===p[1]&&(p[1]="ie");function q(a){for(var b="",c=0;c<a.length;c++)b+=("object"===typeof a[c]?JSON.stringify(a[c]):a[c])+" ";return b.replace(/[\r\n]/g," ").replace("<","&lt;").replace(">","&gt;")}function t(a){window.console&&window.console.log&&(window.GLANCE_COBROWSE?!window.GLANCE_COBROWSE.disableLogging:1)&&window.console.log(q(arguments))}function ba(a){window.console&&window.console.error&&window.console.error(q(arguments))};function u(){this.g={}}u.prototype.add=function(a,b){this.g[a]=this.g[a]||[];this.g[a].push(b)};u.prototype.o=function(a,b){b&&JSON.stringify(b);var c=this.g[a],d=!0;if(void 0===c)return!0;for(a=0;a<c.length;a++)c[a](b)||(d=!1);return d};function ca(a,...b){!window.console||!window.console[a]||window.GLANCE_COBROWSE&&window.GLANCE_COBROWSE.disableLogging||(b=b.map(c=>{if("object"===typeof c)try{c=JSON.stringify(c)}catch(d){console.error(d),c="unable to convert object to string"}return"string"===typeof c?c.replace(/[\r\n]/g," ").replace("<","&lt;"):c}),window.console[a](...b))}function v(...a){ca("log",...a)}function x(...a){ca("error",...a)}function y(...a){v("PRES:",...a)};/*
 Copyright (c) 2022 Glance Networks, Inc.
*/
var da=da||{};window.GLANCE=window.GLANCE||{};window.GLANCE.VERSION="6.19.0.1197459447";window.GLANCE.PATCH="";window.GLANCE.Lib=window.GLANCE.Lib||{};
var ea=function(){var a=navigator.userAgent.toLowerCase(),b=navigator.platform.toLowerCase(),c=a.match(/(edge|edg)[\s\/:]([\w\d\.]+)?/)||a.match(/(opera|ie|firefox|chrome|crios|version)[\s\/:]([\w\d\.]+)?.*?(safari|version[\s\/:]([\w\d\.]+)|$)/)||a.match(/(rv):([\w\d\.]+)/)||[null,"unknown",0];"edg"===c[1]&&(c[1]="edge");"crios"===c[1]?c[1]="chrome":"rv"===c[1]&&(c[1]="ie");a={extend:Function.prototype.extend,name:"version"==c[1]?c[3]:c[1],version:"ie"==c[1]&&document.documentMode||parseFloat("opera"==
c[1]&&c[4]?c[4]:c[2]),D:{name:a.match(/ip(?:ad|od|hone)/)||b.match(/mac/)&&0<typeof navigator.maxTouchPoints?"ios":(a.match(/(?:webos|android)/)||b.match(/mac|win|linux/)||["other"])[0]},ta:{Da:!!document.evaluate,va:!!window.Aa,query:!!document.querySelector,json:!!window.JSON},ua:{},xa:function(){return"ios"==this.D.name||"android"==this.D.name}};document.documentMode&&window.XDomainRequest?(a.name="ie",a.version=document.documentMode):window.navigator&&navigator.appVersion&&-1!=navigator.appVersion.indexOf("MSIE 7.")&&
(a.name="ie",a.version="7");a[a.name]=!0;a[a.name+parseInt(a.version,10)]=!0;a.D[a.D.name]=!0;return a}();function z(){}z.prototype.set=function(a,b){A(window,"clearTimeout",this.g);var c=this;this.g=A(window,"setTimeout",function(){delete c.g;b&&b()},a)};z.prototype.clear=function(){A(window,"clearTimeout",this.g);delete this.g};
function B(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>B(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,e])=>c[d]=B(e,b));return c}return a}if(void 0===C)var C=function(a){return D.g?(Array.prototype.toJSON&&(a=B(a,D.g.window)),D.g.window.JSON.stringify(a)):JSON.stringify(a)};B=function(a,b){if(Array.isArray(a))return(new b.Array(...a)).map(c=>B(c,b));if(null!==a&&"object"===typeof a){const c={};Object.entries(a).forEach(([d,e])=>c[d]=B(e,b));return c}return a};
function fa(a){a.onmessage=function(b){b=JSON.parse(b.data);a.Z&&a.Z(b)};a.H=function(b){b=C(b);a.readyState!==WebSocket.OPEN?x(`Tried to send message on closed websocket: ${b}`):a.send(b)};a.ia=function(b){return b&&b.code||0};a.ja=function(b){return b&&b.reason||""}}function ha(a){a=new WebSocket(a);fa(a);return a}function ia(a,b){A(window,"setTimeout",function(){ia(a,b)},100)}function E(a,b,c){void 0!==a&&(c=c||Object.keys(a),c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])}))}
function ja(a){var b=a.func.split(".");if(2>b.length)x("ERR_BADINVOKE:");else if("GLANCE"===b[0]||"GLANCE_COBROWSE"===b[0]&&"Custom"===b[1]){for(var c=window[b[0]],d=1;d<b.length;d++)if(c=c[b[d]],!c){x("ERR_UNDEFINVOKE:"+b[d]);return}a.args=a.args||{};a.args.remote=!0;c(a.args)}else x("ERR_BADINVOKE:"+b[0])}
async function ka(a,b){return new Promise(async(c,d)=>{b.headers={"Content-Type":"application/json"};"object"===typeof b.body&&(b.body=JSON.stringify(b.body));let e;try{e=await fetch(a,b)}catch(k){x(`JSON request to ${a} failed: ${k.message}`);d("connection");return}if(e.ok){try{var g=await e.json()}catch(k){x(`JSON request to ${a} reponse parse failed`),d("error")}c(g)}else x(`JSON request to ${a} failed status: ${e.status}`),c=await e.text(),x(c),d(401===e.status||403===e.status?"authorization":
"error")})}function F(){da.Ca?this.j=new G("JSON"):this.g=new window.XMLHttpRequest;this.response=null;this.type="JSON"}F.prototype.abort=function(){this.j?this.j.abort():this.g.abort()};
F.prototype.onreadystatechange=function(){if(4==this.g.readyState){A(window,"clearTimeout",this.l);delete this.l;var a="error";if(0==this.g.status)v(this.method+" to "+this.url+" failed: network"),this.h(!0,"connection",this.g.status);else if(200!==this.g.status){x(this.method+" to "+this.url+" failed with status: "+this.g.status);"text"===this.g.responseType&&null!==this.g.responseText&&v(this.g.responseText);if(401===this.g.status||403===this.g.status)a="authorization",this.i&&this.i.T();this.h(!1,
a,this.g.status)}else{if(""!==this.g.response){if("XML"===this.accept)this.response=this.g.responseXML&&this.g.responseXML.documentElement,null===this.response&&x("Invalid XML response: "+this.g.responseText);else if(this.B){for(var b=new Uint8Array(this.g.responseText.length),c=0;c<this.g.responseText.length;c++)b[c]=this.g.responseText.charCodeAt(c)&255;this.response=new Blob([b],{type:this.g.getResponseHeader("Content-Type")})}else if("blob"===this.g.responseType)this.response=this.g.response;
else if(this.g.responseXML)this.response=la(this.g.responseXML.childNodes[0].childNodes[0].nodeValue);else if("HTML"===this.accept||"TEXT"===this.accept)this.response=this.g.responseText;else if(this.response=la(this.g.responseText),null===this.response){v(this.method+" to "+this.url+" failed - can't parse response "+this.g.responseText);this.h(!1,a);return}if(void 0!==this.response.err&&void 0!==this.response.msg){v(this.method+" to "+this.url+" failed with error:"+this.response.err+" "+this.response.msg);
this.h(!1,a);return}}this.onsuccess(this.response)}}};function la(a){var b=null;try{b=JSON.parse(a)}catch(c){return v("JSON parse failed with error: "+c.toString()+" parsing: "+a),null}return b}F.prototype.getResponseHeader=function(a){return this.g.getResponseHeader(a)};F.prototype.get=function(a,b,c,d,e){this.method="GET";H(this,a,null,b,c,d,e)};
function H(a,b,c,d,e,g,k){a.url=b;a.onsuccess=void 0!==g?g:function(){};a.h=void 0!==k?k:function(){};a.method=a.method||"POST";if(a.j)ma(a.j,b,c,d,e,g,k);else{g=a.I||("JSON"===a.type?"application/json; charset=utf-8":"application/x-www-form-urlencoded; charset=utf-8");if("string"===typeof c)var h=c;else c instanceof Blob?(g=c.type,h=c):c&&(h="JSON"===a.type?C(c):"data="+C(c));ea.safari&&a.v&&(a.l=A(window,"setTimeout",function(){v(this.method+" to "+this.url+" failed - timedout (Safari)");this.h(!1,
"timedout")}.bind(a),a.v));a.g.onreadystatechange=function(){a.onreadystatechange()};try{a.g.open(a.method,b,d),void 0!==a.s&&a.g.setRequestHeader("Accept",a.s),void 0!==a.g.setRequestHeader&&"GET"!==a.method&&a.g.setRequestHeader("Content-type",g),a.i&&a.i.F()?a.g.setRequestHeader("Authorization","Bearer "+a.i.F()):a.u&&a.g.setRequestHeader("Authorization","Bearer "+a.u),a.g.withCredentials=e,a.g.send(h)}catch(r){v(a.method+" to "+b+" failed with: "+r.toString()),a.h(!1,r.toString())}}}
function G(a){this.type=a}function ma(a,b,c,d,e,g,k){a.onsuccess=g;a.h=k;ia({from:"IFrameProxyRequest",type:a.type,url:b,obj:c,async:d,withcred:e})}G.prototype.abort=function(){G.postMessage({from:"IFrameProxyRequest",abort:!0})};function I(a){this.name=a}function na(a,b){var c=new Date;c.setUTCHours(c.getUTCHours()+8);try{localStorage.setItem(a.name,C(b)),localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){v("Failed to write cookie: "+a.name)}}
function J(a){if(!oa(a))return null;var b=null;try{b=localStorage.getItem(a.name)}catch(c){return v("Failed to read cookie: "+a.name),null}return JSON.parse(b)}function pa(a,b){"string"===typeof b&&(b=parseInt(b));var c=new Date;c.setUTCMinutes(c.getUTCMinutes()+b);try{localStorage.setItem(a.name+"_exp",c.toGMTString())}catch(d){v("Failed to write cookie: "+a.name)}}
I.prototype.get=function(){if(!oa(this))return null;try{return localStorage.getItem(this.name)}catch(a){return v("Failed to read cookie: "+this.name),null}};function K(a){try{localStorage.removeItem(a.name),localStorage.removeItem(a.name+"_exp")}catch(b){v("Failed to delete cookie: "+a.name)}}function oa(a){var b=null;try{b=localStorage.getItem(a.name+"_exp")}catch(c){return v("Failed to read cookie: "+a.name),!1}if(!b)return!1;b=new Date(b);return b<new Date?(K(a),!1):!0}function D(a){this.g=a}
D.prototype.addEventListener=function(a,b,c){A(this.g,"addEventListener",b,c)};D.prototype.removeEventListener=function(a,b,c){A(this.g,"removeEventListener",b,c)};function A(a,b,...c){return D.g&&a.nodeType?"#document"===a.nodeName?D.g.document[b].apply(a,c):"#document-fragment"===a.nodeName?D.g.DocumentFragment.prototype[b].apply(a,c):D.g.document.body[b].apply(a,c):D.g&&"[object Window]"===a.toString()?D.g.window[b].apply(a,c):a[b].apply(a,c)}
function ra(a,b,c){a.g.style.left=b+"px";a.g.style.top=c+"px"}D.prototype.moveTo=function(a,b){function c(){10>k++?(e+=h,g+=r,ra(d,Math.floor(e),Math.floor(g)),d.h=A(window,"setTimeout",c,20)):ra(d,a,b)}void 0!==this.h&&A(window,"clearTimeout",this.h);var d=this,e=parseInt(this.g.style.left),g=parseInt(this.g.style.top);isNaN(e)&&(e=-999);isNaN(g)&&(g=-999);var k=0,h=(a-e)/10,r=(b-g)/10;0===h&&0===r||c()};function sa(a,b){if(void 0!==a){var c=c||Object.keys(a);c.forEach(function(d){void 0!==a[d]&&(b[d]=a[d])})}}function ta(a){var b={};if(!a)return b;var c=0;for(a=a.attributes;c<a.length;c++){var d=a[c].nodeName.match(/data-(.*)/);d&&2===d.length&&(b[d[1]]=a[c].nodeValue)}return b}function ua(){var a=window.GLANCE_COBROWSE?window.GLANCE_COBROWSE:{},b=document.getElementById("cobrowsescript"),c=document.getElementById("glance-cobrowse");b=ta(b);c=ta(c);sa(b,a);sa(c,a);return a};var L={};f("GLANCE.Authorization",L);L.qa=function(a){L.P=a};L.setToken=L.qa;L.F=function(){var a=ua();return a.authtoken?a.authtoken:L.P||L.m&&J(L.m)};L.T=function(){delete L.P;L.m&&(K(L.m),delete L.m)};L.clearToken=L.T;L.S=function(){return L.F()?!0:!1};L.authorized=L.S;
L.R=async function(a){L.m=L.m||new I("glanceauth");if(!L.S()){var b=`https://${a.ws||"www.glance.net"}/services/AuthorizationService.svc/rest/${a.credentials?"Authorize":"AuthorizeFromWebSession"}?groupid=${a.groupid}&service=${a.service}&duration=${a.duration}&site=${a.site||"production"}`,c;a.credentials?c={method:"post",mode:"cors",body:a.credentials}:c={method:"post",mode:"same-origin",credentials:"include"};try{var d=await ka(b,c)}catch(e){a.onfail(e);return}na(L.m,d);pa(L.m,a.duration)}if(a.onsuccess)a.onsuccess()};
L.authorize=L.R;function M(){}function va(a,b){a.g={};a.g.ws="www.glance.net";a.g.site="production";E(ua(),a.g);E(b,a.g);delete a.g.presenceserver;a.u=!1;a.N=new z;a.I=[];a.j=N;a.l=new I("glance_presence");var c=J(a.l);c&&(0===["visitorid","ws","groupid"].filter(d=>c[d]!==a.g[d]).length?a.i=c.directserver:y("Ignoring glance_presence entry for different webserver, group, or visitor",c.ws,c.groupid,c.visitorid));y("direct server from local storage:",a.i)}var N=1;
function wa(a,b,c,d,e){if(b&&!a.i)t("ERR_NODIRECTSERVER");else{var g=(e||"https")+"://"+(b?a.i:a.g.presenceserver)+"/"+c;d&&(g+="?",["groupid","visitorid"].forEach(function(k){g+=k+"="+a.g[k]+"&"}),g+=`&ver=${l}`);return g}}function xa(a,b){O(a,!1,"findvisitor","GET",b)}
function P(a){t("connecting to "+a.i);a.h&&a.h.close();a.h=ha(wa(a,!0,"agent",!1,"wss"));a.h.$=a.i;a.h.onopen=function(){y("sock onopen, sending connect");a.h.H({type:"connect",authorization:a.s&&a.s.F(),groupid:a.g.groupid,visitorid:a.g.visitorid,guesttoken:a.g.guesttoken,version:l});y("sending message queue");a.I.forEach(function(b){a.h.H(b)});a.I=[];a.j=3};a.h.Z=function(b){t("received:"+C(b));if(a.h){var c=g=>{a.N.clear();a.u||(a.u=!0,a.onvisitorconn(g))},d=b.mtype||b.type,e=b.data;switch(d){case "connected":if(a.g.nokeepalive)break;
y("Keepalive interval: "+b.keepalive);a.v||(a.v=window.setInterval(function(){a.h.H({type:"k"})},1E3*b.keepalive));if(a.onconnected)a.onconnected(e);break;case "invoke":"visitor"===a.ba&&ja(e);break;case "redirect":case "serverclose":e||(e=b);a["on"+d](e);break;case "visitorsock":e.connected?c(e):!e.connected&&a.u&&a.N.set(5E3,()=>{a.u=!1;a.onvisitorconn(e)});break;case "visitorconn":e.connected&&c(e);break;default:if(a["on"+d])a["on"+d](e)}}else y("Ignoring message received after socket close")};
a.h.onclose=function(b){a.h===this&&(t(`presence connection closed ${this.ia(b)} ${this.ja(b)}`),ya(a),za(a))};a.h.onerror=function(b){a.h===this&&(y("socket error"),a.h.onclose(b))}}M.prototype.s=void 0;
function O(a,b,c,d,e){function g(w){var n=w&&(w.directserver||w.direct);!b&&n&&(h.i=n,w.httpsport&&(h.i+=":"+w.httpsport));h.h&&h.i!=h.h.$&&(y("switching connection from "+h.h.$+" to "+h.i),P(h));if(e&&e.onsuccess)e.onsuccess(w)}function k(w,n,qa){t(`Presence request: ${c} failed reason: ${n} http status: ${qa||0}`);503===qa&&(ba("Presence service unavailable"),h.M=!0,n="serviceunavailable");if(e.onfail)e.onfail(n);else Ba(h,{error:"connfail",detail:n})}if(!a.M){var h=a,r=new F;r.i=a.s;r.method=d;
t(c,JSON.stringify(e));Ca(a,function(){h.g.presenceserver&&H(r,wa(h,b,c,!0),e.data?e.data:{},!0,!1,g,k)})}}
function Ca(a,b){if(a.g.presenceserver)b();else{var c=new I("glance_visitor_settings_"+a.g.groupid+"_"+a.g.site),d=J(c);if(d)a.g.presenceserver=d.presenceserver,a.g.isLoadBalanced=d.presencesettings.isPresenceLoadBalanced,a.g.isLoadBalanced&&(a.i=a.g.presenceserver),a.g.presenceserver||t("PRES_DISABLED (from cache)"),b();else{d=new F;var e="https://"+a.g.ws+"/services/authorizationservice/GetVisitorSettings3?groupid="+a.g.groupid+"&site="+a.g.site+"&service=presence";d.method="GET";H(d,e,null,!0,
!1,g=>{a.g.presenceserver=g.presenceUrl;g.isPresenceLoadBalanced&&(a.g.isLoadBalanced=g.isPresenceLoadBalanced,a.i=g.presenceUrl);y("presence service: "+a.g.presenceserver);a.g.presenceserver||t("PRES_DISABLED");var k={};k.presenceserver=a.g.presenceserver;k.presencesettings=g;na(c,k);pa(c,1440);return b()},(g,k)=>{t("PRES_UNAVAILABLE "+k);b()})}}}function ya(a){a.v&&(window.clearInterval(a.v),delete a.v);a.j=N;a.g.isLoadBalanced||(delete a.h,delete a.i)}
function Da(a,b){t("sending",b.type,a.j);3===a.j?(y("sending message: "+JSON.stringify(b)),a.h.H(b)):(y("queuing message: "+JSON.stringify(b)),a.I.push(b),a.connect())}M.prototype.ra=function(a){let b=3===this.j;b&&this.disconnect();this.g.visitorid=a;(b||"api"!==this.g.presence)&&this.connect()};M.prototype.setVisitorId=M.prototype.ra;
M.prototype.connect=function(){if(!this.M)if(this.g.visitorid)if(this.j!==N)y("connect() called when already connecting or connected");else{this.j=2;y("connect");var a=this;this.onscaledown=function(){a.disconnect();a.connect()};this.onredirect=function(b){y("Connected to wrong instance:",JSON.stringify(b),"current direct server:",this.i);this.l&&b.direct!==this.i&&(K(this.l),this.l=new I("glance_presence"),this.disconnect(),za(this))};this.onserverclose=function(){a.disconnect();if(a.onclose)a.onclose()};
Ca(this,()=>{t("visitor settings loaded");this.i?P(this):xa(this,{onsuccess:function(){t("found visitor, connect");P(a)},onfail:function(b){a.j=N;Ba(a,{error:"connfail",detail:b})}})})}else t("CONN_NOVISITORID")};M.prototype.connect=M.prototype.connect;M.prototype.disconnect=function(){y("closewebsocket");this.h&&this.h.close();ya(this);this.l&&K(this.l)};M.prototype.disconnect=M.prototype.disconnect;
function za(a){y(`delayed reconnect.  count: ${a.B||0} connstate: ${a.j}`);a.L||(a.B=a.B||0,a.B++,a.L=window.setTimeout(()=>{delete a.L;a.connect()},3>=a.B?5E3:6E4))}function Ba(a,b){t("Error: ",JSON.stringify(b));a.aa&&a.aa(b);if(a.onerror)a.onerror(b)}M.prototype.o=function(a,b){Da(this,{type:a,data:b})};M.prototype.fire=M.prototype.o;function Q(a){a.uniqueid&&(a.visitorid="UNQ-"+a.uniqueid);va(this,a);this.ba="agent"}f("GLANCE.Presence.Agent",Q);Q.prototype=new M;Q.prototype.s=L;function Ea(a,b,c,d,e){e=e||function(g){v("Unhandled error:"+JSON.stringify(g))};a.g.isLoadBalanced?Da(a,{type:b,data:c}):xa(a,{onsuccess:function(g){g.visitorfound?O(a,!0,"signalvisitor","POST",{data:{mtype:b,data:c},onsuccess:d,onfail:e}):(v("ERR_VISITORNOTPRESENT"),e("visitornotpresent"))},onfail:e})}
Q.prototype.sa=function(a){Ea(this,"signal",a.data,a.onsuccess,a.onfail)};Q.prototype.signalVisitor=Q.prototype.sa;Q.prototype.U=function(a){var b={};E(a,b,["func","args"]);Ea(this,"invoke",b,a.onsuccess,a.onfail)};Q.prototype.invokeVisitor=Q.prototype.U;
Q.prototype.Y=function(a){const b=a.onsuccess;a.onsuccess=function(c){Object.keys(c).forEach(function(d){if("string"===typeof c[d]&&0===c[d].indexOf("{'"))try{y("Converting python object to json:",c[d]),c[d]=JSON.parse(c[d].replace(/'/g,'"'))}catch(e){v("Could not convert "+c[d]+" to json")}});b(c)};O(this,!1,"lookupvisitor","GET",a)};Q.prototype.lookupVisitor=Q.prototype.Y;Q.prototype.query=function(a){O(this,!1,"query","GET",a)};Q.prototype.query=Q.prototype.query;/*
 Copyright (c) 2020-2021 Glance Networks, Inc.
 The GlanceAgent JavaScript can be included in a customer or partner page to join and control
 sessions as an agent, by opening and communicating with /agentjoin/AgentView.aspx
*/
var R=R||{};f("GLANCE.Agent",R);R.A=R.A||{};R.webserver="https://www.glance.net";R.postParametersToViewer=!0;var S={},T={},U=new u,V,W=!1,X=!1;window.addEventListener("message",function(a){const b=a.data.glanceEvent;b&&(a.origin!==R.webserver?t("Glance Agent not handling message from "+a.origin+" not matching "+R.webserver):(U.o(b,a.data.data),U.o("*",a.data)))});function Y(a,b){U.o(a,b);U.o("*",{glanceEvent:a,data:b})}const Fa={C:"cobrowse",G:"screenshare",V:"video"};
R.ma=function(a,b={}){t("GLANCE.Agent.openViewer");var c="";S&&S.partnerid&&S.partneruserid&&S.loginkey&&(c="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey);return R.K(R.webserver+"/agentjoin/AgentView.aspx?SessionKey="+a+"&"+c,b,{pa:"cobrowse",wa:S.partnerid,Ba:a})};R.openViewer=R.ma;
R.K=function(a,b={}){t("GLANCE.Agent.openAgentJoinURL");if(b&&b.iframe){var c="string"===typeof b.iframe?document.getElementById(b.iframe):b.iframe,d,e,g=new Promise((h,r)=>{d=h;e=r});c.onload=function(){let h=c.contentWindow;h?d(h):(Y("iframeblocked",{service:"agent"}),e())};R.postParametersToViewer?Ga(c.contentWindow,a,b):c.src=a;return g}let k;R.postParametersToViewer?(k=window.open("",b.windowName||"_blank",b.windowFeatures||"referrerpolicy==no-referrer,location=no,menubar=0,titlebar=0,status=0,toolbar=0,height=800,width=800,top=10,left=10,scrollbars=1,resizable=1"),
Ga(k,a,b)):k=window.open(a,b.windowName||"_blank",b.windowFeatures||"referrerpolicy==no-referrer,location=no,menubar=0,titlebar=0,status=0,toolbar=0,height=800,width=800,top=10,left=10,scrollbars=1,resizable=1");k?Y("viewerOpened",{service:"agent",close:()=>R.close(k)}):Y("popupblocked",{service:"agent"});return new Promise((h,r)=>{k?h(k):r()})};R.openAgentJoinURL=R.K;
function Ga(a,b,c={}){("undefined"==typeof b||0>b.toLowerCase().indexOf("sessionkey="))&&t("No session key");var d=document.createElement("form");d.method="POST";d.action=R.webserver+"/agentjoin/AgentView.aspx";var e=Z("wait","1");"false"===c.wait&&(e=Z("wait","0"));d.appendChild(e);null!=c.agentVideo&&(e=Z("agentVideo","true"===c.agentVideo?"1":"0"),d.appendChild(e));if(S&&S.partnerid&&S.partneruserid&&S.loginkey){e=Z("loginkey",S.loginkey);var g=Z("partnerid",S.partnerid),k=Z("partneruserid",S.partneruserid);
d.appendChild(e);d.appendChild(g);d.appendChild(k)}e=document.createElement("script");e.innerText="document.forms[0].submit()";d.appendChild(e);e={};if(b){b=b.split("?")[1].split("&");for(h in b){let [w,n]=b[h].split("=");e[w]=n}var h=e}else h={};for(var r in h){b=!1;for(e=0;e<d.elements.length;e++)b=b||d.elements[e].name.toUpperCase()===r.toUpperCase();b?d[r.toUpperCase()].value=h[r]:d.appendChild(Z(r,h[r]))}for(let w in c){r=!1;for(h=0;h<d.elements.length;h++)r=r||d.elements[h].name.toUpperCase()===
w.toUpperCase();r||d.appendChild(Z(w,c[w]))}a.document.body.appendChild(d)}function Z(a,b){var c=document.createElement("input");c.type="hidden";c.name=a.toUpperCase();c.value="undefined"==typeof b?"":b;return c}R.end=function(){t("GLANCE.Agent.end not implemented")};R.end=R.end;R.addEventListener=function(a,b){U.add(a,b)};R.addEventListener=R.addEventListener;R.ca=function(a){U.add("*",function(b){a(b.glanceEvent,b.data)})};R.addEventListenerAll=R.ca;
R.removeEventListener=function(a,b){a=U.g[a];void 0!==a&&(b=a.indexOf(b),0<=b&&a.splice(b,1))};R.removeEventListener=R.removeEventListener;R.da=function(a){t("GLANCE.Agent.authenticate");S=a;for(var b of["idpid","idpname","idptoken","idpusername"])if("undefined"!=typeof S[b]){Ha(b,S[b]);break}};R.authenticate=R.da;
function Ha(a,b){Ia(R.webserver+"/account/getloginkey.aspx?sso=1&mode=embedded&fmt=html&"+(a+"="+b));var c=0;X=!0;var d=setInterval(function(){X?3<c?(X=!1,U.o("authenticateFailed",{}),clearInterval(d)):(c++,t("SAML authentication pending attmept: "+c)):clearInterval(d)},3E3);R.removeEventListener("authenticateSucceeded",Ja);R.addEventListener("authenticateSucceeded",Ja);R.removeEventListener("authenticateFailed",Ka);R.addEventListener("authenticateFailed",Ka)}
function Ia(a){var b=document.createElement("iframe");b.src=a;b.style.display="none";b.style.height="0";b.style.width="0";b.id="glanceSsoIframe";document.body.appendChild(b)}
function Ja(a){X=!1;a=a.loginKey;"undefined"!=typeof a&&0<a.indexOf("~")?(a=a.split("~"),S.loginkey=a[1],0<a[0].indexOf("&")?(a=a[0].split("&"),0==a[0].indexOf("partnerid")?(S.partnerid=a[0].split("=")[1],S.partneruserid=a[1].split("=")[1]):0==a[0].indexOf("partneruserid")?(S.partnerid=a[1].split("=")[1],S.partneruserid=a[0].split("=")[1]):t("Wrong Login Key format")):t("Wrong Login Key format")):t("Wrong Login Key format");null!=document.getElementById("glanceSsoIframe")&&document.getElementById("glanceSsoIframe").remove();
t("SAML authentication succeed")}function Ka(){X=!1;null!=document.getElementById("glanceSsoIframe")&&document.getElementById("glanceSsoIframe").remove();t("SAML authentication failed")}R.la=function(){t("GLANCE.Agent.logout");S={}};R.logout=R.la;
R.X=function(a,b=!0){t("GLANCE.Agent.lookupSession");if(0===Object.keys(S||{}).length)return new Promise((k,h)=>h());var c={index:0,J:!1};let d=()=>{V=null;c.index=0;c.J=!0};V=c;const e=R.webserver+"/services/SessionService.asmx/LookupPartnerSession2";let g="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey+"&ssnkey="+a;return new Promise((k,h)=>{function r(){if(c.J)Y("lookupCanceled",{service:"agent",ssnkey:a}),h();else if(12<=c.index)Y("lookupFailed",{service:"agent",
ssnkey:a,reason:"timedout"}),h();else{Y("lookupWaiting",{service:"agent",ssnkey:a,cancel:d});var w="";fetch(e,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:g}).then(n=>n.text()).then(n=>{w=n;return(new window.DOMParser).parseFromString(n,"text/xml")}).then(n=>{n.getElementsByTagName("agentjoinurl")[0]?(n={service:"agent",id:n.getElementsByTagName("id")[0].textContent,ssnid:n.getElementsByTagName("ssnid")[0].textContent,serverip:n.getElementsByTagName("serverip")[0].textContent,
servername:n.getElementsByTagName("servername")[0].textContent,personid:n.getElementsByTagName("personid")[0].textContent,grpupid:n.getElementsByTagName("groupid")[0].textContent,passcode:n.getElementsByTagName("passcode")[0].textContent,agentjoinurl:n.getElementsByTagName("agentjoinurl")[0].textContent,clientjoinurl:n.getElementsByTagName("clientjoinurl")[0].textContent,calltype:n.getElementsByTagName("calltype")[0].textContent,visitorversion:n.getElementsByTagName("visitorversion")[0].textContent},
Y("lookupFound",n),k(n)):"0"===n.getElementsByTagName("id")[0].textContent?b?setTimeout(r,1E3*(6>=++c.index?3:5)):(Y("lookupFailed",{service:"agent",reason:"not found"}),h()):(Y("lookupFailed",{service:"agent",reason:w}),h())}).catch(n=>{Y("lookupFailed",{service:"agent",reason:w||n.toString()});h()})}}r()})};R.lookupSession=R.X;
R.ka=function(a){t("GLANCE.Agent.inSession");return 0===Object.keys(S||{}).length?new Promise((b,c)=>c()):new Promise(b=>{(function(){Y("inSession",{service:"agent",ssnkey:a});R.O(a).then(c=>{a?b(c.inSession):b(c.sessionsList)})})()})};R.inSession=R.ka;R.W=function(a,b={}){t("GLANCE.Agent.joinSession");const c={groupid:S.partnerid,sskey:a};return new Promise((d,e)=>{let g;R.X(a,null!=(g=b.wait)?g:!0).then(k=>{R.K(k.agentjoinurl,b,{...c,service:Fa[k.calltype]}).then(h=>{d(h)})},e)})};
R.joinSession=R.W;
R.O=function(a){if(0===Object.keys(S||{}).length)return new Promise((d,e)=>e());const b=R.webserver+"/services/SessionService.asmx/AgentInSession";let c="partnerid="+S.partnerid+"&partneruserid="+S.partneruserid+"&loginkey="+S.loginkey+"&ssnkey="+(a||"");return new Promise((d,e)=>{(function(){Y("inSessionLookup",{service:"agent"});fetch(b,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:c}).then(g=>g.text()).then(g=>(new window.DOMParser).parseFromString(g,"text/xml")).then(g=>
{g=g.getElementsByTagName("session2");let k=[];for(let h=0;h<g.length;h++)k.push({id:g[h].getElementsByTagName("id")[0].textContent,ssnkey:g[h].getElementsByTagName("passcode")[0].textContent,num:g[h].getElementsByTagName("num")[0].textContent,disambiguateId:g[h].getElementsByTagName("disambiguateId")[0].textContent,servername:g[h].getElementsByTagName("servername")[0].textContent});d({inSession:0!=g.length,sessionsList:k})}).catch(g=>e(g))})()})};
R.ya=function(a){return 0===Object.keys(S||{}).length?new Promise((b,c)=>c()):new Promise((b,c)=>R.O("").then(d=>{d=d.sessionsList.filter(e=>e.ssnkey==a)[0];void 0===d&&c(`No Session with sessionkey ${a}`);return fetch("https://"+d.servername+"/agent/message",{method:"POST",mode:"cors",cache:"no-cache",credentials:"include",headers:{"Content-Type":"application/json"},redirect:"error",referrerPolicy:"no-referrer",body:"{"+`"ssnid": "${S.partnerid}.${d.ssnkey}.${d.disambiguateId}",`+`"num": ${d.num},`+
'"mtype": "EjectAgent","data": {"reason":"leave"}}'}).then(e=>b(e.ok))}))};R.ea=function(){V&&(t("GLANCE.Agent.cancelLookup"),V.J=!0)};R.cancelLookup=R.ea;R.close=function(a){t("GLANCE.Agent.close");a&&a.close();Y("viewerClosed",{service:"agent"})};R.close=R.close;
R.na=function(a){t("GLANCE.Agent.presenceConnect");return new Promise((b,c)=>{Q||c("Glance Presence Agent undefined");if(0===Object.keys(S||{}).length){let d={pa:"presence",reason:"no credentials"};Y("presenceFailed",d);c(d)}try{console.log(S),L.R({ws:(new URL(R.webserver)).host,service:"presence",credentials:{partneruserid:S.partneruserid,loginkey:S.loginkey,partnerid:S.partnerid},groupid:S.partnerid,duration:120,onsuccess:d=>{Y("presenceAuthorized",{service:"presence",data:d});T=new Q({ws:(new URL(R.webserver)).host,
groupid:S.partnerid,visitorid:a});T.onvisitorconn=e=>{console.log("onvisitorconn","Agent.js");Y("visitorConnected",e);T.Y({onsuccess:g=>{Y("visitorData",g);b(g)},onfail:g=>{Y("lookupFailed",g);c(g)}})};T.onpresence=e=>{Y("presence",e)};T.onterms=e=>{"DECLINED"==e.status.toUpperCase()&&(W=!1);Y("presenceOnTerms",e)};T.onvisitorsessionend=e=>{W=!1;Y("presenceSessionEnd",e)};T.onerror=e=>{Y("presenceError",e)};T.onvisibility=e=>{Y("presenceVisibility",e)};T.connect()},onfail:d=>{Y("presenceFailed",{service:"presence",
reason:d});c(d)}})}catch(d){Y("presenceFailed",{service:"presence",reason:d}),c(d)}})};R.presenceConnect=R.na;
R.oa=function(a,b,c){t("GLANCE.Agent.presenceStartSession");let d=b||{};d.func=d.func||"GLANCE.Cobrowse.VisitorUI.showTerms";d.args=d.args||{};let e=a||d.args.sessionKey||Math.floor(1E4*Math.random());return new Promise(function(g,k){Q||k("Glance Presence Agent undefined");d.args.sessionKey=e;d.onfail=function(h){Y("presenceInvokeFailed",{service:"presence",reason:h});k(h)};T.onvisitorsessionstart=()=>{W?(Y("presenceSessionStart",{}),g(R.W(e,c))):(t("GLANCE.Agent not handling visitorsessionstart, this agent did not invoke startsession"),
k())};W=!0;T.U(d)})};R.presenceStartSession=R.oa;
R.A.fa=function(){function a(){try{let b=window.AgentData;if(b)return b.privs.ENABLEOCR="off",console.log("URL validation disabled"),!0}catch(b){console.error(b.toString()+": Could not access AgentData. disableUrlValidation method can only be called from the agentviewer window.")}return!1}if(!a())if(window.GLANCE&&window.GLANCE.Cobrowse&&window.GLANCE.Cobrowse.Agent)console.log("Defer disableURLValidation"),window.GLANCE.Cobrowse.Agent.addEventListener("agents",a);else return console.error("GLANCE.Cobrowse.Agent not defined. disableUrlValidation method can only be called from the agentviewer window."),
!1;return!0};f("GLANCE.Agent.Screenshare.disableUrlValidation",R.A.fa);R.A.ga=function(){try{let a=window.GLANCE_SESSIONINFO||JSON.parse(document.getElementById("glance-ssninfo").getAttribute("data-ssninfo"));return JSON.parse(a.agentscreenshareallowedurls).filter(b=>b.allowed).map(b=>b.url)}catch(a){return console.error(a.toString()+": Could not access SessionInfo. getAllowedUrls method can only be called from the agentviewer window"),null}};f("GLANCE.Agent.Screenshare.getAllowedUrls",R.A.ga);
R.ha=function(){try{return"on"===(window.AgentData||JSON.parse(document.getElementById("agentviewinfo").getAttribute("data-agentdata"))).privs.ENABLEOCR}catch(a){return console.error(a.toString()+": Could not access AgentData. getUrlValidationEnabled method can only be called from the agentviewer window."),null}};R.getUrlValidationEnabled=R.ha;R.za=function(){t("GLANCE.Agent.presenceDisconnect");T.disconnect()};window.addEventListener("unload",function(){console.log("unload")});}).call(window);
//# sourceMappingURL=map.js.map
